## YAML Template.
---
server:
    port: 9000
    
spring:
    application:
        name: API-GATEWAY
    cloud:
        gateway:
                mvc:
                    routes:
                        - id: produk
                          uri: lb://produk-service
                          predicates: 
                            - Path=api/produk/**
                        - id: pelanggan
                          uri: lb://pelanggan-service
                          predicates: 
                            - Path=api/pelanggan/**
                        - id: order
                          uri: lb://order-service
                          predicates: 
                            - Path=api/order/**
                          
                    
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance: 
        hostname: localhost